### ISSUE TITLE
[BUG] `%position%` has weird content

### ISSUE THREAD

**Issue by Purpzie** [hypherionmc/simple-rpc-public#17]
**Describe the bug**
Using `%position%` shows weird content

**To Reproduce**
Put this in your config:

```toml
[general]
	clientID = 893309240318509096
	# ...

[single_player]
	enabled = true
	description = "Singleplayer"
	state = "%position%"
	largeImageKey = "logo"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""
	buttons = []
```

**Expected behavior**
`%position%` should probably just show as `X, Y, Z` or `x=X y=Y z=Y`

**Screenshots**
![image](https://user-images.githubusercontent.com/25022704/135552806-55bed826-4765-44b8-988e-6aee50525900.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - **OS:** Windows 10 64-Bit (10.0.19041)
 - **JAVA Version:** 16
 - **Mod Version:** 1.17-2.4-fabric
 - **Discord Version:** Stable 99811 (bc84d34)
 - **Minecraft Version:** 1.17.1
 - ~~Forge~~ **Fabric Version:** fabric-loader-0.11.7-1.17.1
