### ISSUE TITLE
[BUG] The server icon is not displayed correctly.

### ISSUE THREAD

**Issue by XtoManuel** [hypherionmc/simple-rpc-public#92]
**Describe the bug**
Reviewing the documentation I found an error:
`%server%` shows the server IP replacing the . with _
`%servericon%` is the variable that contains the icon information
![image](https://github.com/user-attachments/assets/249eb663-8c32-4709-abd8-891be531669a)

**To Reproduce**
1. Configure the large image to be that of the server using the variable `%servericon%`
2. Reload the configuration
3. The image loaded is that of the minecraft icon and not that of the server
![image](https://github.com/user-attachments/assets/1815e5d7-9917-4195-bcb1-676a557efda1)

**Expected behavior**
I have verified that %servericon% obtains the server icon correctly, verifying that the url returns the image, but it is not loaded in the RPC.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11
 - JAVA Version:
 - Mod Version: 3.3.2
 - Discord Version: stable 315866 (7042d52) Host 1.0.9157 x64 (50412) Build Override: N/A Windows 11 64-bit (10.0.22631)
 - Minecraft Version: 1.19.2
 - Forge/Fabric Version: Forge 43.3.8

**Comment by Kaleidio** [comment]
please send where in the config you put the %servericon% variable, as you may have entered it in the incorrect section, or with a syntax error.

**Comment by XtoManuel** [comment]
I currently have the server closed, so the information cannot be obtained currently.

```toml
#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "%servername%"
	#The second line of text under the app name
	state = "%players% jugador(es) online"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%servericon%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%servericon%" #"%mcinfo% | %mods% mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%playerhead%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player%"
	#The buttons to display on Discord
	buttons = []
```
